#server:
#  port: 6000
#spring:
#  application:
#    name: springbootConfig
#  profiles:
#    active: subversion
#  cloud:
#    config:
#      server:
#        svn:
#          uri: https://MSI:8443/svn/project/microlaw/config
#          #username: project
#          #password: 0212
#          default-label:
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:5000/eureka/
#  instance:
#    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 30